services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_started
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    env_file:
      - .env-docker
    working_dir: /rails
  postgresql:
    image: postgres:18
    volumes:
      - db_data18:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h postgresql
      interval: 5s
  dragonfly:
    image: ghcr.io/dragonflydb/dragonfly:v1.36.0
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: minio server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniodevelopment
    volumes:
      - minio_data:/data
volumes:
  db_data18:
  dragonflydata:
  minio_data:
  bundle:
